# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Remind
# tagline:          'A Jekyll theme'
# description:      'The <a href="http://hyde.getpoole.com" target="_blank">Hyde</a> theme for <a href="http://jekyllrb.com" target="_blank">Jekyll</a>, refreshed.'
url:              https://xtozero.github.io
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'BongSeok Cho'
  url:            https://github.com/xtozero

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
# version:            3.4.1
# sidebar_home_link:  true
github:
  repo:             https://github.com/xtozero

comments: false
